#!/usr/bin/env python3
"""Generate an LLDB command file entry point from a Natvis file.

The command file is intentionally small: it imports the generated Python
formatter module, which keeps support for synthetic children and CustomListItems.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from natvis_to_lldb import write_formatter


def _quote_lldb_path(path: Path) -> str:
    text = str(path)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _default_python_output(command_file: Path) -> Path:
    if command_file.name == "lldb_formatters.txt":
        return command_file.with_name("lldb_formatters.py")
    return command_file.with_suffix(".py")


def write_command_file(command_file: Path, python_file: Path) -> None:
    command_file.parent.mkdir(parents=True, exist_ok=True)
    python_path = python_file.resolve()
    command_file.write_text(
        "\n".join(
            [
                "# Generated by natvis_to_lldb_txt.py.",
                "# Load with: command source /path/to/lldb_formatters.txt",
                "command script import " + _quote_lldb_path(python_path),
                "",
            ]
        ),
        encoding="utf-8",
    )


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate lldb_formatters.txt and a companion Python formatter from Natvis."
    )
    parser.add_argument("natvis", type=Path, help="Input .natvis file.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("lldb_formatters.txt"),
        help="Generated LLDB command file path.",
    )
    parser.add_argument(
        "--python-output",
        type=Path,
        help="Generated Python formatter path. Defaults next to the command file.",
    )
    parser.add_argument(
        "--category",
        default="natvis_generated",
        help="LLDB formatter category name.",
    )
    parser.add_argument(
        "--fail-on-warning",
        action="store_true",
        help="Return a non-zero exit code if unsupported Natvis nodes are found.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    command_file = args.output
    python_file = args.python_output or _default_python_output(command_file)

    result = write_formatter(args.natvis, python_file, args.category)
    write_command_file(command_file, python_file)

    print(
        f"Generated {command_file} and {python_file} with {len(result.types)} formatter(s)."
    )
    if result.warnings:
        print("Warnings:", file=sys.stderr)
        for warning in result.warnings:
            print(f"  - {warning}", file=sys.stderr)
        if args.fail_on_warning:
            return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
